pagenot found

diff --git a/0x0C-web_server/4-not_found_page_404 b/0x0C-web_server/4-not_found_page_404
--- a/0x0C-web_server/4-not_found_page_404
+++ b/0x0C-web_server/4-not_found_page_404
@@ -1,26 +1,48 @@
 #!/usr/bin/env bash
-# A bash script that installs nginx on an ubuntu machine.
-# This scripts also configures the default webpage served to be "Hello World!"
-# When request url matches /redirect_me, it redirects to my youtube channel.
-# When a page/file not found in the document root is requested, the 404.html
-# page is served to the client as stated with the error_page directive.
+# Configures a new ubuntu machine by installing
+# Nginx where it should be listening on port 80
+# Serve a page that would return a Hello World string
 
-sudo apt-get update -y
+set -e  # Exit immediately if a command exits with a non-zero status
+set -u  # Treat unset variables as an error
 
-sudo apt-get install nginx -y
+if [[ $EUID -ne 0 ]]; then
+   echo "This script must be run as root" 
+   exit 1
+fi
 
-echo "Hello World!" | sudo dd status=none of=/var/www/html/index.html
+NGINX_CONF="/etc/nginx/sites-available/default"
 
-echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null
+echo -e "Updating and installing Nginx.\n"
+apt-get update -y -qq && \
+	 apt-get install nginx -y
 
-NEW_RULE="\\\n\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/@nwodothomas7963;\n\t}\n"
+echo -e "\nSetting up some minor stuff.\n"
 
-sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup
+# starting nginx service
+service nginx start
 
-sudo sed -i "53i $NEW_RULE" /etc/nginx/sites-available/default
+# allowing nginx on firewall
+ufw allow 'Nginx HTTP'
 
-NEW_RULE="\\\n\terror_page 404 /404.html;\n\n\tlocation = /404.html {\n\t\tinternal;\n\t}\n"
+# Give the user ownership to website files for easy editing
+chown -R "$USER":"$USER" /var/www/html
+chmod -R 755 /var/www
 
-sudo sed -i "53i $NEW_RULE" /etc/nginx/sites-available/default
+# Backup default index
+cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
 
-sudo service nginx reload
+# Creating new index
+echo -e "Hello World!" > /var/www/html/index.nginx-debian.html
+
+# Setting up /redirect_me to a youtube video
+sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/@nwodothomas7963 permanent;' "$NGINX_CONF"
+
+# Set up a 404 page
+echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
+sed -i '25i\	error_page 404 /error_404.html;' "$NGINX_CONF"
+
+# Restarting nginx
+service nginx restart
+
+echo -e "\nCompleted.\n"
